# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAreCorrectproducts():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_areCorrectproducts(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.maximize_window()
    self.driver.find_element(By.ID, "user-name").click()
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    self.driver.find_element(By.ID, "login-button").click()
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-backpack").click()
    self.vars["Sauce Labs Backpack"] = self.driver.find_element(By.CSS_SELECTOR, "#item_4_title_link > .inventory_item_name").text
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-bike-light").click()
    self.vars["Sauce Labs Bike Light"] = self.driver.find_element(By.CSS_SELECTOR, "#item_0_title_link > .inventory_item_name").text
    self.driver.find_element(By.XPATH, "//div[3]/a").click()
    self.vars["Sauce Labs Backpack"] = self.driver.find_element(By.CSS_SELECTOR, "#item_4_title_link > .inventory_item_name").text 
    self.vars["Sauce Labs Bike Light"] = self.driver.find_element(By.CSS_SELECTOR, "#item_0_title_link > .inventory_item_name").text 
    assert self.driver.find_element(By.CSS_SELECTOR, "#item_4_title_link > .inventory_item_name").text == "Sauce Labs Backpack"
    assert self.driver.find_element(By.CSS_SELECTOR, "#item_0_title_link > .inventory_item_name").text == "Sauce Labs Bike Light"
  
